apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nginx-ns1"
  namespace: akuity
spec:
  project: default
  source:
    repoURL: https://github.com/damir385/test-lab1.git
    targetRevision: "HEAD"
    path: charts/nginx-0.1.0
    helm:
      parameters:
        - name: replicaCount
          value: "3"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "ns1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true